### PR TITLE
Client credentials authorization

### PR DESCRIPTION
**Pull request by svishnyakoff**
Server-side authentication using introspection endpoint and oauth2 bearer token 
https://github.com/micronaut-projects/micronaut-security/issues/91

Based on the discussion on the ticket the default behaviour was extended with caching capabilities to improve performance characteristics. Although initially proposed default behaviour by @jameskleeh  to make cache enabled by default, I faced with certain difficulties.

A cache in Micronaut is usually configured through either yml file that later captured `DefaultSyncCache` or configured directly via underlying jcache provider. Irrespective of cache provider and it's the implementation the cache default configuration should be consistent. That being said there is no to setup default cache configuration for jcache providers.

### CODE REVIEW

**Comment by svishnyakoff** [comment]
@jameskleeh Please have a look at the basic implementation. Note that it covers only server-side authorization,  all the work related to enhancing http client will be done in the scope of separate PR.    Keeping it in small chunks that are getting merged, will work as a motivator for me and further contribution :)

If the basic implementation is fine, I will extend the PR with the documentation changes.

**Comment by svishnyakoff** [comment]
@jameskleeh Just a friendly reminder that this buddy is waiting for your review

**Comment by reinkrul** [comment]
Awesome work @svishnyakoff, we could really use this feature, too.

**Comment by sdacode** [comment]
Awesome work @svishnyakoff , we could really use this feature, too.

We have the same need here, is there a possibility of this implementation to be included in the project ?

**Comment by graemerocher** [comment]
Seems to be already integrated https://micronaut-projects.github.io/micronaut-security/latest/guide/#clientcredentials ?

**Comment by sdacode** [comment]
Yes, but was not included in fully implementation?

For the implementation of it completely served RFC7662, where I can validate a Opaque Token in a resource server ...
If I get a Opaque Token, and with the current implementation I can not forward to a Resource Server (/ token_info).

What I need is exactly the example of the documentation
https://tools.ietf.org/html/rfc7662#section-2

    In this Example, The Protected Resource Uses a Client Identifier and
    Client Secret to Authenticate Itselle to the Introspection Endpoint.
    The Protected Resource Also Sends to Token Type Hint Indicating That
    It is inquiring About an Access Token.

    The Following is Non-Normative Example Request:

      Post / Introspect http / 1.1
      Host: Server.example.com
      Accept: Application / JSON
      Content-Type: Application / X-www-Form-Urlencoded
      Authorization: BASIC CZZCAGRSA3F0MZPNWDFMQMF0M2JW

      token = mf_9.b5f-4.1JQM & token_type_hint = access_token

**Comment by jameskleeh** [comment]
> with the current implementation I can not forward to a Resource Server (/ token_info).

Why not?

**Comment by sdacode** [comment]
I'm following the documentation
https://micronaut-projects.github.io/micronaut-security/latest/guide/#introspection

application.yml
```
  security:
    oauth2:
      clients:
        mycompany:
          introspection:
            url: "https://xxxxxxx/api/oauth/token_info"
            auth-method: 'client_secret_post'
```
Console:

DEBUG i.m.s.t.reader.HttpHeaderTokenReader - Looking for bearer token in Authorization header
DEBUG i.m.s.t.reader.DefaultTokenResolver - Token <MY_BEARER_OPAQUE_TOKEN> found in request POST /xxx/yyy
DEBUG i.m.s.t.jwt.validator.JwtValidator - Validating signed JWT
DEBUG i.m.security.filters.SecurityFilter - No Authentication fetched for request. POST /xxx/yyy.
DEBUG i.m.s.rules.AbstractSecurityRule - None of the given roles [[isAnonymous()]] matched the required roles [[isAuthenticated()]]. Rejecting the request
DEBUG i.m.security.filters.SecurityFilter - Unauthorized request POST /xxx/yyy. The rule provider io.micronaut.security.rules.SecuredAnnotationRule rejected the request.

**In my humble evaluation:**
Token validation goes to **JwtValidator**, method validate(SignedJWT jwt)
But there is no signatures configured, the list is empty and always returns optional.empty ()

```
private Optional<JWT> validate(SignedJWT jwt) {
        if (LOG.isDebugEnabled()) {
            LOG.debug("Validating signed JWT");
        }

        final JWSAlgorithm algorithm = jwt.getHeader().getAlgorithm();

        List<SignatureConfiguration> sortedConfigs = new ArrayList<>(signatures);
        sortedConfigs.sort(comparator(algorithm));

        for (SignatureConfiguration config: sortedConfigs) {
          .....
        }
        
        return Optional.empty();
    }
```

Java version: 11
Micronaut: 2.4.2

**Comment by jameskleeh** [comment]
As it says in the documentation: "It is possible to configure the introspection endpoint URL for OAuth 2.0 and OpenID providers, however Micronaut currently does not use this configuration in any way"

The `/token_info` endpoint exposed by Micronaut security, documented [here](https://micronaut-projects.github.io/micronaut-security/latest/guide/#introspectionendpoint) is for tokens that are setup to be validated by Micronaut. That would require some configuration to say what the signature/encryption/jwks endpoint is.

You would have to call the endpoint from the provider to get information from any access token returned from a client credentials token request.

**Comment by sujeet100** [comment]
Is this PR merged? I could not find any of the classes in the PR in the latest version of the micronaut security libs
Neither there is any documentation around it.

**Pull request closed without merging**
