### PR TITLE
[WIP] Make Authorization header prefix check case insensitive

### PR DESCRIPTION
**Pull request by jcassee**
See #252

### CODE REVIEW

**Comment by graemerocher** [comment]
Maybe the change should include `toLowerCase(Locale.ENGLISH)` as it could break depending on the system locale?

**Comment by jcassee** [comment]
> Maybe the change should include `toLowerCase(Locale.ENGLISH)` as it could break depending on the system locale?

Or `Locale.ROOT`? A quick "find usages" in my IDE finds many similar case-insensitive checks around HTTP are using it.

**Comment by jcassee** [comment]
Question: is using a stub the preferred way of testing an abstract class? The Spock docs mention using a partial mock using `Spy`, but from a quick search through the project code, I don't see `Spy` used anywhere.

**Comment by sdelamo** [comment]
Thanks for the PR @jcassee 

> Question: is using a stub the preferred way of testing an abstract class? The Spock docs mention using a partial mock using `Spy`, but from a quick search through the project code, I don't see `Spy` used anywhere.

Yes, in general we don't use `Spy`.

**Pull request merged**
