### PR TITLE
Small refactoring of TokenAuthenticationFetcher

### PR DESCRIPTION
**Pull request by dstepanov**

### CODE REVIEW

**Comment by dstepanov** [comment]
@graemerocher @jameskleeh This is also some small refactoring pending for some days. Should I make a PR to target master?

**Comment by dstepanov** [comment]
BTW build failing is not related to this PR

**Comment by graemerocher** [comment]
@dstepanov yes I plan to look at this failure shortly

**Comment by dstepanov** [comment]
@sdelamo Can you check this one also

**Pull request merged**
