### PR TITLE
DefaultSecurityService should use RolesFinder

### PR DESCRIPTION
**Pull request by dstepanov**
Custom roles finder should provider roles for the security service, `DefaultRolesFinder` didn't check if tone configuration is enabled or not.

### CODE REVIEW

**Comment by traycho** [comment]
What if roles are not provided from the token ?

Having roles as part of Authentication just as an attribute (as it is right now)  sounds better for abstraction how roles are populated.

**Comment by dstepanov** [comment]
@traycho There is already `RolesFinder` that is doing the extraction, the problem is if you provide custom impl. `SecurityService` is not going to pick up your new roles which is a bug.

**Comment by dstepanov** [comment]
@traycho Check `DefaultRolesFinder`

**Comment by dstepanov** [comment]
@graemerocher @jameskleeh Can somebody take a look at this one? We override `RolesFinder` but `SecurityService` is not using it which I think is not correct.

**Comment by dstepanov** [comment]
@sdelamo Would you have time to review this pr?

**Comment by sdelamo** [comment]
Thanks for the PR @dstepanov I will review this now.

**Comment by sdelamo** [comment]
Closed via https://github.com/micronaut-projects/micronaut-security/pull/328

**Comment by sdelamo** [comment]
@dstepanov The PR closing this will fix this for Micronaut Security 2.x Do you need this fix for 1.4.x. branch ?

**Pull request closed without merging**
