### PR TITLE
Load JWT roles into Authentication

### LINKED ISSUE #495: JWT roles are ignored when creating UserDetails
Hello!

What is the reason for the [createAuthentication(JWT token)](https://github.com/micronaut-projects/micronaut-security/blob/7c044c50407f6258e95b93a0f6a0a0e97d918dcb/security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/DefaultJwtAuthenticationFactory.java#L57) to ignore the roles from the token, even tho they match the default `roles` attribute name?

For instance, when sending this JWT on a request:

```json
{
  "exp": 1607657258,
  "iat": 1607653658,
  "jti": "cf8dab3c-9588-4a42-bb8d-d0e5dd8a64c8",
  "iss": "http://localhost:8000/auth/realms/micronaut",
  "sub": "c412a536-afd7-4e73-8974-dd9fd5a48e77",
  "typ": "Bearer",
  "azp": "micronaut",
  "session_state": "1d10f641-df33-4680-ac3f-ef3f35976080",
  "acr": "1",
  "scope": "profile",
  "roles": [
    "ROLE_ADMIN"
  ],
  "name": "Administrator",
  "tenant": "8576dbec-659c-44aa-a70d-d6a4e673567c",
  "username": "admin@admin.com"
}
```

It will be ignored:

oie_hDmmiyp4WxrZ

The reason for that is the use of a hardcoded `Collections.emptyList()` to set the roles when creating the `UserDetails`, as shown in that link.

If this was a mistake, I can send a PR to fix this issue.

Best regards,
Rafael Pacheco.

### PR DESCRIPTION
**Pull request by rafaelrenanpacheco**
- Fixes #495

### CODE REVIEW

**Comment by rafaelrenanpacheco** [comment]
Seems like the jobs successfully finished, but this is breaking it:

```
Posting status 'completed' with conclusion 'success' to https://github.com/micronaut-projects/micronaut-security/pull/498 (sha: 19476f37f5be76e8532d3ea3893ccb6910637a57)
Error: Resource not accessible by integration
```

**Comment by rafaelrenanpacheco** [comment]
@alvarosanchez any clue on what is breaking here? Something tried to `Posting status 'completed' with conclusion 'success'` and failed.

**Comment by alvarosanchez** [comment]
It is a known issue: https://github.com/micronaut-projects/micronaut-project-template/issues/62

You can simply ignore the error. If the step "Build with Gradle" is passing, then consider it working.

**Comment by sdelamo** [comment]
Close via: https://github.com/micronaut-projects/micronaut-security/pull/508

**Pull request closed without merging**
