### PR TITLE
issues_1071 Oauth 2.0 password authentication does not work

### PR DESCRIPTION
**Pull request by uulyar**
Oauth 2.0 password authentication does not work with openId configuration

Closed issue [1071](https://github.com/micronaut-projects/micronaut-security/issues/1071)

### CODE REVIEW

**Review by sdelamo — CHANGES_REQUESTED** [review]
Can you add a test?

**Comment by uulyar** [comment]
yes, soon

**Comment by sdelamo** [comment]
@uulyar you need to sign the CLA as well

**Comment by sdelamo** [comment]
Close via https://github.com/micronaut-projects/micronaut-security/pull/1087

**Pull request closed without merging**
