### PR TITLE
feat: add introspection endpoint

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by graemerocher** [comment]
@sdelamo was this reviewed by someone?

**Comment by sdelamo** [comment]
Yes, James review it.

**Comment by graemerocher** [comment]
ok, if you can make that visible in terms of requesting a review in future since it seemed like it was not the case from the PR history

**Comment by sdelamo** [comment]
> ok, if you can make that visible in terms of requesting a review in future since it seemed like it was not the case from the PR history

Will do.

**Pull request merged**
