### PR TITLE
breaks: delete deprecated code

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@wetted please add the necessary accept-api changes and docs for this breaking changes.

**Review by wetted — APPROVED** [review]
I see there is a breaking changes document in the user guide, that just notes deprecated code is removed. Is that enough?

**Comment by wetted** [comment]
> I see there is a breaking changes document in the user guide, that just notes deprecated code is removed. Is that enough?

never mind. Now I see you comment asking me to do that. :)

**Comment by wetted** [comment]
ping @sdelamo I think this is now GTG

**Pull request merged**
