### PR TITLE
Move to jakarta packages.

### PR DESCRIPTION
**Pull request by altro3**
Fixes for gradle version catalog.
Removed unnecessary libs from catalog.
micronaut-views 4.0.0-SNAPSHOT

### CODE REVIEW

**Comment by altro3** [comment]
@graemerocher Hmm... I tried to figure out what was wrong with this test, but I couldn't. I can say for sure that this is not related to the transition to jakarta or the update of com.sun.activation:javax.activation to org.eclipse.angus:angus-activation. I think I need help :-(

**Comment by graemerocher** [comment]
might be related to secrets

**Comment by sdelamo** [comment]
Thanks for the PR @altro3 

However, I have encapsulated the move from `javax.validation` to `jakarta.validation` in its own PR  #1250  to avoid mixing several things in the same PR.

**Comment by altro3** [comment]
@graemerocher @sdelamo I have only one question about the testcontainers library: IDEA shows me that this library is already in one of the version directories, which is very logical and correct in my opinion, but if I remove these versions from the libs.versions.toml file, then gradle does not find their.

In general, I would like to know: is there a version of testcontainers in the micronaut-test versions directory and if so. why can't you use it.

By the way, I think that selenium should also be present in the micronaut test version directory

**Comment by altro3** [comment]
The same question about `libs.junit.jupiter.engine.` Why I can't use it from other versions catalog?

**Comment by altro3** [comment]
@graemerocher @sdelamo Found problem - that was my mistake here:
изображение

**Comment by sdelamo** [comment]
Thanks of the PR. Incorporated your changes via: #1258 #1257 #1256 #1253 #1252 #1251 #1259

**Comment by altro3** [comment]
@sdelamo thanks! But you lost some changes. See this: https://github.com/micronaut-projects/micronaut-security/pull/1260

**Pull request closed without merging**
