### PR TITLE
Conditional eager initializiation of OpenID providers

### PR DESCRIPTION
**Pull request by adamkobor**
Provides a better workaround for: https://github.com/micronaut-projects/micronaut-security/issues/604

### CODE REVIEW

**Comment by adamkobor** [comment]
kindly pinging @sdelamo regard this PR :)

**Comment by sdelamo** [comment]
> kindly pinging @sdelamo regard this PR :)

I have this on top of my queue for monday. Thanks for the patience @adamkobor

**Comment by adamkobor** [comment]
> > kindly pinging @sdelamo regard this PR :)
> 
> I have this on top of my queue for monday. Thanks for the patience @adamkobor

np, thanks for the heads up and also have a nice weekend!

**Comment by sdelamo** [comment]
this PR is related to  #868

**Comment by sdelamo** [comment]
@adamkobor , I think [using `@Parallel` and `@Context` is a better solution to avoid blocking the Netty event loop](https://github.com/micronaut-projects/micronaut-security/pull/1140) ). Thanks for raising this PR and pushing us towards finding a solution.

**Comment by adamkobor** [comment]
> @adamkobor , I think [using `@Parallel` and `@Context` is a better solution to avoid blocking the Netty event loop](https://github.com/micronaut-projects/micronaut-security/pull/1140). Thanks for raising this PR and pushing us towards finding a solution.

No problem, I'm glad if I could help a bit :)

**Pull request closed without merging**
