### PR TITLE
Add SameSite property to JwtConfigurationProperties

### PR DESCRIPTION
**Pull request by abedurftig**
PR for https://github.com/micronaut-projects/micronaut-security/issues/217

### CODE REVIEW

**Comment by abedurftig** [comment]
I have signed the CLA twice. Not sure why it is still showing as pending.

**Comment by graemerocher** [comment]
You need to do the commits with the same github account as your submit the PR with. The username in the commits differ

**Comment by abedurftig** [comment]
Building the 1.3.x branch locally with Java 8 works. Maybe the issue is bumping the Micronaut version to 1.3.4. Maybe some breaking changes.

**Comment by graemerocher** [comment]
Reported https://github.com/micronaut-projects/micronaut-security/issues/220

**Comment by jameskleeh** [comment]
Thanks for the contribution!

**Pull request merged**
