### PR TITLE
Add support for GraalVM

### PR DESCRIPTION
**Pull request by ilopmar**

### CODE REVIEW

**Comment by graemerocher** [comment]
Thinking about this I think it should be in core as that is where caffeine lives

**Comment by ilopmar** [comment]
Which submodule and package should I use? `runtime` and `io.micronaut.cache` package?

**Comment by ilopmar** [comment]
Sorry, there is already a `io.micronaut.cache.graal` package there

**Comment by ilopmar** [comment]
Superseded by https://github.com/micronaut-projects/micronaut-core/pull/2931

**Pull request closed without merging**
