### PR TITLE
doc: example evaluating HTTP Request Body for a SecurityRule like decision

### PR DESCRIPTION
**Pull request by sdelamo**
close https://github.com/micronaut-projects/micronaut-security/issues/689

### CODE REVIEW

**Comment by sdelamo** [comment]
@jameskleeh could you please review this?

**Comment by jameskleeh** [comment]
I'm not really sure we should be documenting this. From the use cases I've heard, the requirement was to verify the body matches a given signature. For that type of use case using a Netty handler would be far more reliable. `request.getBody(Map)` infers that the body can be converted to a Map, which isn't always the case. Can you explain the use case you're trying to document?

**Comment by sdelamo** [comment]
After discussing this with @jameskleeh we are going to close this PR. He is going to document how to use a Netty Handler for this use case.

**Comment by kanak-kabara** [comment]
@jameskleeh Has this been documented anywhere, apologies if it has.

**Pull request closed without merging**
