### PR TITLE
migrate to build plugin 6.1.1 and new Micronaut BOM/Platform architecture, fix checkstyle config

### PR DESCRIPTION
**Pull request by wetted**

### CODE REVIEW

**Comment by wetted** [comment]
This has issues with broken tests due to Multiple possible bean candidates found errors. I'm also investigating other tests that may have different issues (e.g. missing snakeyaml possibly).

**Comment by graemerocher** [comment]
There error:

```
Failed to inject value for parameter [tenantResolver] of class: io.micronaut.security.token.multitenancy.principal.BookService

Message: Multiple possible bean candidates found: [PrincipalTenantResolver, $PrincipalTenantResolver$Definition$Intercepted]
Path Taken: new Bootstrap() --> Bootstrap.setBookService([BookService bookService]) --> new BookService([TenantResolver tenantResolver])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [tenantResolver] of class: io.micronaut.security.token.multitenancy.principal.BookService

Message: Multiple possible bean candidates found: [PrincipalTenantResolver, $PrincipalTenantResolver$Definition$Intercepted]
Path Taken: new Bootstrap() --> Bootstrap.setBookService([BookService bookService]) --> new BookService([TenantResolver tenantResolver])
```

Requires recompiling the `micronaut-multitenant` project with the latest snapshot of Micronaut 4

**Comment by graemerocher** [comment]
There are 2 failures remaining:

1. This one will pass if the multi tenancy module is rebuilt with the latest snapshot of Micronaut 4 https://ge.micronaut.io/s/ovy4ksntwo6qc/tests/:security-jwt:test/io.micronaut.security.token.multitenancy.principal.PrincipalTenantResolverSpec/setup%20gorm%20server?top-execution=1 
2. This one will pass if the 3.9.x branch is merged into the 4.0.x branch and then into master (not sure of the branching structure of this project) https://ge.micronaut.io/s/ovy4ksntwo6qc/tests/:security:test/io.micronaut.docs.security.authorization.X509AuthorizationSpec/test%20custom%20X509%20authentication%20fetcher?top-execution=1

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
> 2\. (not sure of the branching structure of this project)

Same as other projects. `master` points to 4.0.x of `core`. There are branches for every minor versions.

**Pull request merged**
